name:                bytecode
version:             0.1.0.0
github:              "max0x4e/bytecode"
license:             BSD3
author:              "Max Belov"
maintainer:          "maxim.belov@northstar.systems"
copyright:           "2021 Maxim Belov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/max0x4e/bytecode#readme>

dependencies:
- base >= 4.7 && < 5
- mtl 
- Stack 
- regex-compat
- unordered-containers 

library:
  source-dirs: src

executables:
  bytecode-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytecode
    - filepath

tests:
  bytecode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bytecode
    - hspec
